// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDis8h3dOmIOJ6057RrDKPv_f4FzOAhXnQ',
    appId: '1:51824385064:web:56537b896c20bde3ee291d',
    messagingSenderId: '51824385064',
    projectId: 'gobind-745f8',
    authDomain: 'gobind-745f8.firebaseapp.com',
    storageBucket: 'gobind-745f8.appspot.com',
    measurementId: 'G-B7QPWLTJJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWIorZ2E338YZDsbpQHH1XMTRZufz-z9w',
    appId: '1:51824385064:android:db523c2c550e5b6eee291d',
    messagingSenderId: '51824385064',
    projectId: 'gobind-745f8',
    storageBucket: 'gobind-745f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLKIiuaUEiF8ObrOevRQqDImK5ISCURtk',
    appId: '1:51824385064:ios:854dfa7cf1e2029dee291d',
    messagingSenderId: '51824385064',
    projectId: 'gobind-745f8',
    storageBucket: 'gobind-745f8.appspot.com',
    androidClientId: '51824385064-e1n7dq2mrkuss75451fka0rqrcpphdji.apps.googleusercontent.com',
    iosClientId: '51824385064-5ob8gd35easq8bjprdf7tu9f2mpg0dqu.apps.googleusercontent.com',
    iosBundleId: 'com.portfolio.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLKIiuaUEiF8ObrOevRQqDImK5ISCURtk',
    appId: '1:51824385064:ios:854dfa7cf1e2029dee291d',
    messagingSenderId: '51824385064',
    projectId: 'gobind-745f8',
    storageBucket: 'gobind-745f8.appspot.com',
    androidClientId: '51824385064-e1n7dq2mrkuss75451fka0rqrcpphdji.apps.googleusercontent.com',
    iosClientId: '51824385064-5ob8gd35easq8bjprdf7tu9f2mpg0dqu.apps.googleusercontent.com',
    iosBundleId: 'com.portfolio.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDis8h3dOmIOJ6057RrDKPv_f4FzOAhXnQ',
    appId: '1:51824385064:web:0498e0968b61afb5ee291d',
    messagingSenderId: '51824385064',
    projectId: 'gobind-745f8',
    authDomain: 'gobind-745f8.firebaseapp.com',
    storageBucket: 'gobind-745f8.appspot.com',
    measurementId: 'G-RTKYJWYFNQ',
  );
}
